import { StyleSheet } from "react-native";

import { colors } from "../../colors.js";

export default StyleSheet.create({
    profile_container: {
        flex: 1,
        width: "100%",
        backgroundColor: colors.background_secondary,
    },
    profile_banner: {
        height: 180,
        width: "100%",
        backgroundColor: colors.violet,
        position: "relative",
    },
    profile_banner_pen: {
        position: "absolute",
        right: 10,
        top: 8,
    },
    log_out: {
        position: "absolute",
        left: 10,
        top: 8,
    },
    profile_column: {
        width: "100%",
        paddingLeft: 15,
        paddingRight: 15,
        position: "relative",
        top: -90,
        marginTop: 30,
    },
    profile_column_box: {
        width: "100%",
        borderWidth: 2,
        borderColor: colors.background_secondary,
        paddingTop: 15,
        backgroundColor: colors.action_tertiary,
        borderRadius: 5,
        marginBottom: 30,
    },
    profile_sigla_container: {
        width: 120,
        height: 120,
        borderRadius: 60,
        borderWidth: 2,
        borderColor: colors.foreground_tertiary,
        alignSelf: "center",
    },
    profile_sigla_box: {
        width: "100%",
        height: "100%",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: colors.violet,
        borderRadius: 60,
        borderWidth: 3,
        borderColor: colors.action_tertiary,
    },
    profile_sigla: {
        color: colors.foreground_primary,
        fontSize: 25,
        fontWeight: "500",
    },
    profile_username: {
        color: colors.foreground_primary,
        alignSelf: "center",
        fontSize: 24,
        fontWeight: "500",
        marginTop: 20,
    },
    profile_member_since: {
        paddingLeft: 15,
        paddingRight: 15,
        marginTop: 45,
        paddingTop: 15,
        paddingBottom: 25,
        width: "100%",
        borderWidth: 2.5,
        borderColor: "transparent",
        borderTopColor: colors.background_secondary,
    },
    member_since_txt: {
        alignSelf: "center",
        color: colors.foreground_secondary,
        marginTop: 10,
        marginBottom: 10,
        fontWeight: "500",
    },

    profile_column_box_title: {
        color: colors.foreground_secondary,
        marginTop: 10,
        marginBottom: 10,
        fontWeight: "600",
        paddingLeft: 15,
        paddingRight: 15,
        fontSize: 18,
    },
    profile_column_box_text: {
        color: colors.foreground_tertiary,
        marginTop: 4,
        marginBottom: 10,
        paddingLeft: 15,
        paddingRight: 15,
        fontSize: 15,
    },
    profile_add_info_box: {
        width: "100%",
        paddingLeft: 15,
        paddingRight: 15,
        paddingTop: 10,
        paddingBottom: 20,
    },
    profile_add_info: {
        width: "100%",
        height: 80,
        borderWidth: 0.5,
        borderColor: colors.violet,
        borderRadius: 5,
        alignItems: "center",
        justifyContent: "center",
    },
    login_box: {
        width: "90%",
        backgroundColor: colors.action_tertiary,
        paddingBottom: 50,
        paddingLeft: 18,
        paddingRight: 18,
    },
    login_h1: {
        color: colors.foreground_primary,
        fontSize: 20,
        fontWeight: "600",
        alignSelf: "center",
        marginTop: 50,
        marginBottom: 40,
    },
    input: {
        width: "100%",
        height: 60,
        backgroundColor: colors.background_secondary,
        color: colors.foreground_secondary,
        marginBottom: 18,
        fontSize: 16,
        borderRadius: 5,
        alignSelf: "center",
        paddingLeft: 8,
        paddingRight: 8,
        borderWidth: 0.5,
        borderColor: colors.violet,
    },
    login_text: {
        color: colors.foreground_secondary,
        fontSize: 16,
        alignSelf: "center",
        marginTop: 20,
        marginBottom: 20,
    },
    login_text_violet: {
        color: colors.violet,
    },
    login_button: {
        backgroundColor: colors.violet,
        width: "100%",
        height: 50,
        alignSelf: "center",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 5,
    },
    login_button_text: {
        color: colors.foreground_primary,
        fontWeight: "500",
    },
});
